# Generated by Django 4.0 on 2022-01-13 10:17

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funuser', '0004_alter_funuser_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fnotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=2048, verbose_name='Content')),
                ('additional_files', models.FileField(help_text='If you have more than one file, please package them and upload them.', upload_to='', verbose_name='Additional files')),
                ('DOC', models.DateTimeField(auto_now_add=True, verbose_name='Date of creating')),
                ('DOU', models.DateTimeField(auto_now=True, verbose_name='Date of updating')),
                ('comment', models.TextField(max_length=128, verbose_name='Comment')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this notification belongs to. all user of specific groups will receive notification. for all users if groups is null', related_name='notification_set', related_query_name='notification', to='auth.Group', verbose_name='groups')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funuser.funuser', verbose_name='Author')),
                ('readers', models.ManyToManyField(blank=True, related_name='reader_set', related_query_name='reader', to=settings.AUTH_USER_MODEL, verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
