# Generated by Django 3.2.4 on 2021-06-12 14:05

import uuid

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import funfile.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Label name')),
                ('comment', models.CharField(max_length=64, verbose_name='Label comment')),
                ('cover', models.ImageField(blank=True, upload_to=funfile.storage.upload_to, verbose_name='Label cover')),
                ('creating_date', models.DateTimeField(auto_now_add=True, verbose_name='Label creating date')),
                ('is_legal', models.BooleanField(default=True, verbose_name='合法 ?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Label author')),
            ],
            options={
                'verbose_name': 'Eduhub label',
                'verbose_name_plural': 'Eduhub  labels',
            },
        ),
        migrations.CreateModel(
            name='Funtest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('test_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Test commit')),
                ('test_text', models.TextField(max_length=12288, verbose_name='Template text')),
                ('submitting_date', models.DateTimeField(auto_now_add=True, verbose_name='Test submitting date')),
                ('last_modifying_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modifying date')),
                ('test_commit', models.CharField(blank=True, max_length=64, null=True, verbose_name='Test commit')),
                ('test_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Test owner')),
            ],
            options={
                'verbose_name': 'Eduhub Test',
                'verbose_name_plural': 'Eduhub Tests',
            },
        ),
        migrations.CreateModel(
            name='Funcontent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Content title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=2048, verbose_name='Content')),
                ('classification', models.CharField(blank=True, max_length=64, null=True, verbose_name='Content classification')),
                ('uploading_date', models.DateTimeField(auto_now_add=True, verbose_name='Content uploading date')),
                ('comment', models.TextField(max_length=64, verbose_name='Content comment')),
                ('is_legal', models.BooleanField(default=True, verbose_name='Is content legal')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduhub.label', verbose_name='Content label')),
            ],
            options={
                'verbose_name': 'Eduhub content (NEW)',
                'verbose_name_plural': 'Eduhub contents (NEW)',
            },
        ),
        migrations.CreateModel(
            name='Funclassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Classification name')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Classification level')),
                ('creating_date', models.DateTimeField(auto_now_add=True, verbose_name='Classification creating date')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Is classification disabled')),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Classification creating user')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='eduhub.funclassification', verbose_name='Parent classification')),
            ],
            options={
                'verbose_name': 'Eduhub classification',
                'verbose_name_plural': 'Eduhub classifications',
            },
        ),
        migrations.CreateModel(
            name='Eduhubhomesticker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Eduhub homepage sticker title')),
                ('subtitle', models.TextField(max_length=64, verbose_name='Eduhub homepage sticker subtitle')),
                ('cover', models.ImageField(upload_to=funfile.storage.upload_to, verbose_name='Eduhub homepage sicker cover')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('promulgating_date', models.DateTimeField(auto_now_add=True, verbose_name='Eduhub homepage sticker promulgating date')),
                ('comment', models.TextField(max_length=128, verbose_name='Eduhub homepage sticker comment')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隐藏(不贴) ?')),
                ('promulgator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Eduhub homepage sticker promulgator')),
            ],
            options={
                'verbose_name': 'Eduhub homepage sticker',
                'verbose_name_plural': 'Eduhub homepage stickers',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Content title')),
                ('content_file', models.FileField(blank=True, upload_to=funfile.storage.upload_to, verbose_name='Content file')),
                ('uploading_date', models.DateTimeField(auto_now_add=True, verbose_name='Content uploading date')),
                ('comment', models.TextField(max_length=64, verbose_name='Content comment')),
                ('is_legal', models.BooleanField(default=True, verbose_name='Is content legal')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduhub.label', verbose_name='Content label')),
            ],
            options={
                'verbose_name': 'Eduhub content',
                'verbose_name_plural': 'Eduhub contents',
            },
        ),
    ]
