# Generated by Django 3.2.7 on 2021-10-04 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0005_auto_20211004_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='parent_id',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='eduhub.classification',
                verbose_name='Parent classification ID'),
        ),
    ]
