# Generated by Django 3.2.7 on 2021-10-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0007_alter_classification_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
