# Generated by Django 3.2.7 on 2021-10-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0008_rename_parent_id_classification_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='parent',
        ),
    ]
