# Generated by Django 3.2.7 on 2021-10-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0010_classification_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='eduhub.classification',
                verbose_name='Parent classification'),
        ),
    ]
