# Generated by Django 3.2.7 on 2021-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0011_alter_classification_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='comment',
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name='Classification comment'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(
                max_length=64,
                verbose_name="Classification name('/' cannot be included)"),
        ),
    ]
