# Generated by Django 3.2.7 on 2021-10-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0021_auto_20211006_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asharinggroupmember',
            old_name='classification',
            new_name='gclassification',
        ),
    ]
