# Generated by Django 4.0 on 2022-01-10 17:00

from django.db import migrations, models
import eduhub.models


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0027_alter_appraising_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asharinggroup',
            name='cover',
            field=models.ImageField(blank=True, upload_to=eduhub.models.asharinggroup_upload_to, verbose_name='Group cover'),
        ),
        migrations.AlterField(
            model_name='eduhubhomesticker',
            name='cover',
            field=models.ImageField(upload_to=eduhub.models.eduhubhomesticker_upload_to, verbose_name='Eduhub homepage sicker cover'),
        ),
        migrations.AlterField(
            model_name='label',
            name='cover',
            field=models.ImageField(blank=True, upload_to=eduhub.models.label_upload_to, verbose_name='Label cover'),
        ),
    ]
