# Generated by Django 4.0 on 2022-01-10 07:23

import uuid

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funuser', '0003_auto_20211006_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fblog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=2048, verbose_name='Content')),
                ('DOC', models.DateTimeField(auto_now_add=True, verbose_name='Date of appraising content creating')),
                ('DOU', models.DateTimeField(auto_now=True, verbose_name='Date of appraising content updating')),
                ('comment', models.TextField(max_length=128, verbose_name='Eduhub homepage sticker comment')),
                ('is_legal', models.BooleanField(default=True, verbose_name='Is content legal?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funuser.funuser', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
