# Generated by Django 4.0 on 2022-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fblog',
            name='DOC',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creating'),
        ),
        migrations.AlterField(
            model_name='fblog',
            name='DOU',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of updating'),
        ),
        migrations.AlterField(
            model_name='fblog',
            name='comment',
            field=models.TextField(max_length=128, verbose_name='Comment'),
        ),
    ]
