# Generated by Django 4.0 on 2022-01-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnotification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fnotification',
            old_name='groups',
            new_name='receiving_groups',
        ),
    ]
